"""Database schema SQL snippets for Stock Lab admin/setup screens.

Keep runtime DB access in app.py for now; this module only owns static DDL/RLS
SQL text so UI code is not carrying schema definitions.
"""


SWING_RADAR_CREATE_SQL = """
create table if not exists swing_radar (
  owner_email text not null,
  ticker text not null,
  name text,
  asset_class text default '',
  idea text default '',
  check_1 text default '',
  check_2 text default '',
  check_3 text default '',
  risk_1 text default '',
  risk_2 text default '',
  risk_3 text default '',
  entry_rule text default '',
  exit_rule text default '',
  next_event text default '',
  status text default '대기',
  decision text default '관망',
  importance text default '중',
  reference_link text default '',
  last_checked text default '',
  memo text default '',
  primary key (owner_email, ticker)
);

alter table swing_radar enable row level security;

drop policy if exists swing_radar_owner_select on swing_radar;
drop policy if exists swing_radar_owner_insert on swing_radar;
drop policy if exists swing_radar_owner_update on swing_radar;
drop policy if exists swing_radar_owner_delete on swing_radar;

create policy swing_radar_owner_select
on swing_radar for select
using (owner_email = coalesce(auth.jwt() ->> 'email', ''));

create policy swing_radar_owner_insert
on swing_radar for insert
with check (owner_email = coalesce(auth.jwt() ->> 'email', ''));

create policy swing_radar_owner_update
on swing_radar for update
using (owner_email = coalesce(auth.jwt() ->> 'email', ''))
with check (owner_email = coalesce(auth.jwt() ->> 'email', ''));

create policy swing_radar_owner_delete
on swing_radar for delete
using (owner_email = coalesce(auth.jwt() ->> 'email', ''));
""".strip()


FEEDBACK_CREATE_SQL = """
create table if not exists feedback (
  id bigint generated by default as identity primary key,
  owner_email text not null,
  category text not null default '개선 제안',
  title text not null default '',
  body text not null default '',
  priority text not null default '보통',
  status text not null default '접수',
  created_at timestamptz not null default now()
);

create index if not exists feedback_owner_email_idx on feedback(owner_email);
create index if not exists feedback_created_at_idx on feedback(created_at desc);

alter table feedback enable row level security;

drop policy if exists feedback_owner_select on feedback;
drop policy if exists feedback_owner_insert on feedback;
drop policy if exists feedback_owner_update on feedback;
drop policy if exists feedback_owner_delete on feedback;

create policy feedback_owner_select
on feedback for select
using (owner_email = coalesce(auth.jwt() ->> 'email', ''));

create policy feedback_owner_insert
on feedback for insert
with check (owner_email = coalesce(auth.jwt() ->> 'email', ''));

create policy feedback_owner_update
on feedback for update
using (owner_email = coalesce(auth.jwt() ->> 'email', ''))
with check (owner_email = coalesce(auth.jwt() ->> 'email', ''));

create policy feedback_owner_delete
on feedback for delete
using (owner_email = coalesce(auth.jwt() ->> 'email', ''));
""".strip()


SIGNAL_JOURNAL_CREATE_SQL = """
create table if not exists signal_journal (
  id bigint generated by default as identity primary key,
  owner_email text not null,
  signal_date date not null default current_date,
  created_at timestamptz not null default now(),
  source text not null default '',
  ticker text not null,
  name text not null default '',
  asset_class text not null default '',
  decision_label text not null default '',
  decision_code text not null default '',
  decision_group text not null default '',
  final_read text not null default '',
  signal_side text not null default 'neutral',
  price numeric,
  macro_state text not null default '',
  safety_state text not null default '',
  fin_score numeric,
  target_weight numeric,
  current_weight numeric,
  weight_gap numeric,
  rr_ratio numeric,
  rsi numeric,
  mfi numeric,
  pct_b numeric,
  snapshot jsonb not null default '{}'::jsonb,
  unique (owner_email, signal_date, source, ticker, decision_code, final_read)
);

create index if not exists signal_journal_owner_email_idx on signal_journal(owner_email);
create index if not exists signal_journal_signal_date_idx on signal_journal(signal_date desc);
create index if not exists signal_journal_ticker_idx on signal_journal(ticker);

alter table signal_journal enable row level security;

drop policy if exists signal_journal_owner_select on signal_journal;
drop policy if exists signal_journal_owner_insert on signal_journal;
drop policy if exists signal_journal_owner_update on signal_journal;
drop policy if exists signal_journal_owner_delete on signal_journal;

create policy signal_journal_owner_select
on signal_journal for select
using (owner_email = coalesce(auth.jwt() ->> 'email', ''));

create policy signal_journal_owner_insert
on signal_journal for insert
with check (owner_email = coalesce(auth.jwt() ->> 'email', ''));

create policy signal_journal_owner_update
on signal_journal for update
using (owner_email = coalesce(auth.jwt() ->> 'email', ''))
with check (owner_email = coalesce(auth.jwt() ->> 'email', ''));

create policy signal_journal_owner_delete
on signal_journal for delete
using (owner_email = coalesce(auth.jwt() ->> 'email', ''));
""".strip()


def get_swing_radar_create_sql() -> str:
    return SWING_RADAR_CREATE_SQL


def get_feedback_create_sql() -> str:
    return FEEDBACK_CREATE_SQL


def get_signal_journal_create_sql() -> str:
    return SIGNAL_JOURNAL_CREATE_SQL
