AUTH_MODE = "password"
APP_PASSWORD = "dmdwnsc0587##"

SUPABASE_URL = "https://bmoxdueczkxqplvwaupq.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "sb_secret_RyEkXxuXOdluV97jBj45Sw_q2zAqfti"

ALLOWED_EMAILS = ["kej0587@gmail.com"]
ADMIN_EMAILS = ["kej0587@gmail.com"]

fmp_api_key = "uUMjWTgf3eL0qiPxQx07q2M11DOTkYUt"
dart_api_key ="d30af980502d18960f63b00d8a0ad28a61823346"

[auth]
redirect_uri = "https://saminsky.streamlit.app/oauth2callback"
cookie_secret = "mystockapp_2026_qp9vK2xL8sN4zR7hT1bC6dE9fG3jH5kM0pQ"
client_id = "105094532714-52v5monct1htdcnn5dcu8hrdhjm1nim4.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"